config/routes.rb
Rails.application.routes.draw do

  devise_for :users ,:controllers => { :registrations => "registrations" }
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  # get 'signup', to: 'users#new'
  # get  'login',  to: 'sessions#new'
  # post 'login',  to: 'sessions#create'
  # delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
  resources :users, except:[:new]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title , presence: true, length: {
                minimum: 3,
                maximum: 100
  }
  validates :description, presence: true, length: {
      minimum: 3,
      maximum: 5000
  }
  validates :user_id,presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles,through: :article_categories


  validates :name ,presence: true,length:{ minimum: 3,maximum: 25}
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable ,authentication_keys: [:username]

  has_many :articles, dependent: :destroy
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # helper_method :current_user,:logged_in?,:require_user
  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end
  # def logged_in?
  #   !!current_user
  # end
  # def require_user
  #   if !logged_in?
  #     flash[:danger] = "You must be Logged in to perform that action"
  #     redirect_to root_path
  #   end
  # end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article,only: [:edit,:update,:show,:destroy]
    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end
    def new
        @article = Article.new
    end

    def edit

    end

    def update
        if @article.update(article_params)
            flash[:success] = "Article was successfully update"
        redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    def create
        #render plain: params[:article].inspect
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
         flash[:success] = "Article was successfully created"
         redirect_to article_path(@article)
        else
          render 'new'
        end
        #redirect_to article_path(@article)
    end

    def show

    end

    def destroy
        @article.destroy
        flash[:danger] = "You deleted an Article"
        redirect_to articles_path
    end

    private

    def article_params
        params.require(:article).permit(:title,:description, category_ids:[])
    end

    def set_article
        @article = Article.find(params[:id])
    end

    def require_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:danger] = "You must be Logged in to perform that action"
            redirect_to root_path
        end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only:[:show,:edit,:update]
  before_action :require_admin,except: [:index,:show]
  def index
    @categories = Category.paginate(page: params[:page], per_page:5)
  end

  def new
    @category = Category.new
  end

  def show

    @category_articles = @category.articles.paginate(page: params[:page],per_page: 3)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @category.update(category_params)
      flash[:success] = "Category name was succesfully Updated"
      redirect_to category_path(@category)
    else
       render 'edit'
    end
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
  def require_admin
    if !user_signed_in? || (user_signed_in? && !current_user.admin?)
      flash[:danger] = "Access Restiction for Admins ONly"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username,:email,:password])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username,:password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:email,:password])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have sucessfully Logged In"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your log in information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit,:update,:show,:destroy]
  before_action :require_same_user,only:[:edit,:update]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page],per_page:5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to ALpha blog #{@user.username}"
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "You updated your account Successfully"
      redirect_to articles_path
    else
       render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page],per_page:5)
  end

  def destroy
    @user.destroy
    flash[:danger] = "User and all the articles created by the user have been deleted"
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username,:email,:password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = "You must be Logged in to perform that action"
      redirect_to root_path
    end
  end

  def require_admin
    if user_signed_in? && !current_user.admin?
      flash[:danger] = "Only Admin can use this action"
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size:80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size= options[:size]
    gravatar_url = "//0.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url,alt: user.username,class: "img-circle")
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <h3> <%= link_to article.title.upcase, article_path(article) %></h3>
        </div>
        <div class="article-body">
          <%= truncate(article.description.capitalize, length: 50) %>
          <div class="articles-meta-details">
            <small>Created by: <%= article.user.username %> , <%= time_ago_in_words(article.created_at) %>,
              Last updated <%= time_ago_in_words(article.updated_at) %></small>
          </div>
        </div>
        <% if article.categories.any? %>
          <p>Categories : <%= render article.categories %></p>
        <% end %>
        <div class="article-actions">
          <% if user_signed_in? && current_user == article.user  %>
            <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-success" %>
            <%= link_to "Delete this Article", article_path(article), method: :delete,
                        data: {confirm: "Are you sure to delete this Article"},
                        class: "btn btn-xs btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/error', obj: @article %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for @article, html: {class: "form-horizontal", role: "form"} do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2 ">
          <%= f.label :title %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :title, class: "form-control", placeholder: " Title of The Article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :description, class: "form-control", placeholder: "Article Description", rows: 10 %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <%= cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-8">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-6 pull-right">
      <%= link_to "Cancel request return to article list", articles_path %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit existing Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center"> LIST OF ALL THE ARTICLES</h1>
<div class="center">
  <%= will_paginate  %>
</div>
<%= render 'article' ,obj: @articles %>
<div class="center">
  <%= will_paginate  %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center">Create an Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"> Title : <%= @article.title.upcase %></h2>

<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
    <ul class="listing">
      <div class="row center">

        <div class="col-md-4 col-md-offset-4">
          <li>Created by</li>
          <li><%= link_to gravatar_for(@article.user, size: 80), user_path(@article.user) %></li>
          <li class="article-title">
            <%= link_to @article.user.username, user_path(@article.user) %>
          </li>
          <li>
            <small><%= pluralize(@article.user.articles.count, "Article") if @article.user.articles %></small>
          </li>
        </div>
      </div>
    </ul>
  <% end %>
  <h4 class="pull-left description"><Strong>Description :</Strong></h4>
  <br>
  <hr>
  <%= simple_format(@article.description) %>
  <% if @article.categories.any? %>
    <p>Categories : <%= render @article.categories %></p>
  <% end %>
  <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
    <div class="article-actions">
      <%= link_to "View all the Articles", articles_path, class: "btn btn-xs btn-primary" %>
      <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-success" %>
      <%= link_to "Delete this Article", article_path(@article), method: :delete, data: {confirm: "Are you sure to delete this Article"}, class: "btn btn-xs btn-danger" %>
    </div>
  <% end %>
</div>

app/views/categories/_category.html.erb
<span class="">
  <%= link_to category.name , category_path(category),class:"label label-primary" %> &nbsp
</span>

app/views/categories/_form.html.erb
<%= form_for @category, html:{class: "form-horizontal",role: "form" } do |f| %>
  <div class="form-group">
    <div class="control-label col-sm-2 ">
      <%= f.label :name  %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :name, class: "form-control",placeholder:"Category Name",autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-8">
      <%= f.submit class: "btn btn-primary btn-lg" %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render 'categories/form' %>

app/views/categories/index.html.erb
<h1 class="text-center">Categories</h1>
<div class="center">
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="article-title">
            <%= link_to "#{category.name}", category_path(category), class: "label label-primary" %>
          </li>
          <% if user_signed_in? and current_user.admin? %>
            <%= link_to "Edit Category Name", edit_category_path(category) %>
          <% end %>
          <li>
            <small> <%= pluralize(category.articles.count, "article") %></small>
          </li>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<%= render 'shared/error', obj: @category %>
<h1 class="text-center">Create a new category</h1>
<%= render 'categories/form' %>
<div class="col-xs-4 col-xs-offset-6 pull-right">
  <%= link_to "Cancel request return to article list", users_path %>
</div>

app/views/categories/show.html.erb
<h1 class="text-center"><%= "Category : #{@category.name}" %></h1>
<div class="center">
  <% if user_signed_in? and current_user.admin? %>
    <%= link_to "Edit Category Name", edit_category_path(@category), class: "center label label-primary" %>
  <% end %>
  <%= will_paginate @category_articles %>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div class="center">
  <%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-copyright text-center py-3">
    &copy 2018 Copyright:
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do|name , msg | %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div,msg, id:"flash#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>


  </div>
</div>

app/views/layouts/_navigator.html.erb
<nav class="navbar navbar-custom">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar">s</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to "Users", users_path %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Articles<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Articles", articles_path %></li>
              <li><%= link_to "Add new Article", new_article_path %></li>
            </ul>
          </li>
        <% else %>
          <li> <%= link_to "Articles", articles_path %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All categories", categories_path %></li>
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
            <% if user_signed_in? && current_user.admin?%>
              <li><%= link_to "Create new Category", new_category_path %>
            <% end %>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              Your Profile <%= "ADMIN" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">

              <li><%= link_to "Edit Profile", edit_user_path(current_user) %>></li>
              <li><%= link_to "View Your Page", user_path(current_user) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in ", new_user_session_path %> </li>
          <li><%= link_to "Sign up", new_user_registration_path %> </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlogv3</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<%= render 'layouts/navigator' %>
<%= render 'layouts/messages' %>
<div class="container content">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<h1>this is about page</h1>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>ALPHA BLOG</h1>
  <p><%= link_to "Sign up now",new_user_registration_path, class:"btn btn-primary btn-lg" %></p>
  <p align="left"><%= link_to "About Us",about_path, class:"btn btn-primary btn-sm" %></p>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <ul>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(articles.errors.count, "error") %>
              prohibited this article from being saved
            </h2>
            <div class="panel-body">
              <% articles.errors.full_messages.each do |msg| %>
                <li> <%= msg %>  </li>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </ul>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/error', obj: @user %>
<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title"><%= test %></h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-xs-12">
        <%= form_for @user, :html => {class: "form-horizontal", role: "form"} do |f| %>
          <div class="form-group">
            <div class="control-label col-sm-2 ">
              <%= f.label :username %>
            </div>
            <div class="col-md-8">
              <%= f.text_field :username, class: "form-control",
                               placeholder: "Enter your username", autofocus: true %>
            </div>
          </div>
          <div class="form-group">
            <div class="control-label col-sm-2">
              <%= f.label :email %>
            </div>
            <div class="col-md-8">
              <%= f.text_field :email, class: "form-control", placeholder: "Enter your email" %>
            </div>
          </div>
          <div class="form-group">
            <div class="control-label col-sm-2">
              <%= f.label :password %>
            </div>
            <div class="col-md-8">
              <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-8">
              <%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: "btn btn-primary btn-lg")
              %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center">Edit your account</h1>
<%= render 'users/form' ,test: "Edit USER ACCOUNT"%>

app/views/users/index.html.erb
<h1 class="text-center"> All alpha bloggers</h1>
<div class="center">
  <div class="center">
    <%= will_paginate %>
  </div>
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <li class="article-title">
            <%= link_to user.username, user_path(user) %>
          </li>
          <li>
            <small><%= pluralize(user.articles.count, "Article") if user.articles %></small>
          </li>
          <% if user_signed_in? && current_user.admin? %>
            <li> <%= link_to "Delete this user", user_path(user), method: :delete,
                             data: {confirm: "Are you sure to delete the user and all of his articles"},
                             class: "btn btn-sm btm-danger" %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <div class="center">
    <%= will_paginate %>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'users/form' , test: "Sign up" %>

app/views/users/show.html.erb
<h1 class="text-center"> Welcome to <%= @user.username %> 's  page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user,size:150 %>
  </div>
</div>
<h4 class="text-center"><%= @user.username %>'s Articles</h4>
<div class="center">
  <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article' ,obj: @user_articles %>
<div class="center">
  <%= will_paginate  @user_articles %>
</div>